; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
; Global Lean GCC Size Optimizations for all boards
build_flags = 
    -flto                       ; Link Time Optimization
    -Wl,--relax                 ; Instruction Relaxation
build_unflags =
    -fno-lto

; Ensure MIDIUSB is only included when needed
lib_ldf_mode = chain+

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = 
    ${env.build_flags}
    -D BOARD_NANO
build_src_flags = 
    -fno-threadsafe-statics

[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
build_flags = 
    ${env.build_flags}
    -D BOARD_PRO_MICRO
build_src_flags = 
    -fno-threadsafe-statics
